"""
Django settings for gdc_kraken project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import json

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
config_file_path = BASE_DIR / "config.json"
if not config_file_path.exists():
    raise Exception(f"Missing config.json ({config_file_path})")
with config_file_path.open('r', encoding='utf-8') as file:
    config_data = json.load(file)

def _env(name, default=None):
    """Lit une variable d'environnement, sinon la valeur config.json, sinon default."""
    if name in os.environ:
        return os.environ[name]
    if name in config_data:
        return config_data[name]
    return default

def _env_bool(name, default=False):
    raw = _env(name)
    if raw is None:
        return default
    if isinstance(raw, bool):
        return raw
    return str(raw).strip().lower() in ("1", "true", "yes", "on")

SECRET_KEY = _env("SECRET_KEY")
if not SECRET_KEY:
    raise Exception("SECRET_KEY is required (env or config.json)")

PLATFORM = _env("PLATFORM", "DEV")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG env override ; sinon False pour PROD/DOCKER.
if "DEBUG" in os.environ:
    DEBUG = _env_bool("DEBUG")
else:
    DEBUG = PLATFORM not in ("PROD", "DOCKER")

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("ALLOWED_HOSTS", "localhost,grecedecanards.fr").split(",")
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

# Derrière un reverse-proxy (Traefik, nginx, Cloudflare…)
# Activé par défaut en DOCKER/PROD ; override via env si besoin.
_PROXY_DEFAULT = PLATFORM in ("DOCKER", "PROD")
USE_X_FORWARDED_HOST = _env_bool("USE_X_FORWARDED_HOST", _PROXY_DEFAULT)
USE_X_FORWARDED_PROTO = _env_bool("USE_X_FORWARDED_PROTO", _PROXY_DEFAULT)
if USE_X_FORWARDED_PROTO:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# COOP/COEP ne s'appliquent que sur origines « trustworthy » (HTTPS, localhost).
# Désactivé par défaut pour accès HTTP direct (ex. IP:6140) ; activer derrière HTTPS prod.
if _env_bool("ENABLE_COOP", False):
    SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
else:
    SECURE_CROSS_ORIGIN_OPENER_POLICY = None


# Application definition

# --- Auth sociale optionnelle (Discord / Steam) ---
DISCORD_CLIENT_ID = (_env("DISCORD_CLIENT_ID") or "").strip()
DISCORD_CLIENT_SECRET = (_env("DISCORD_CLIENT_SECRET") or "").strip()
STEAM_API_KEY = (_env("STEAM_API_KEY") or "").strip()
AUTH_DISCORD_ENABLED = _env_bool("AUTH_DISCORD_ENABLED", False)
AUTH_STEAM_ENABLED = _env_bool("AUTH_STEAM_ENABLED", False)

SOCIAL_AUTH_ENABLED = {
    "discord": AUTH_DISCORD_ENABLED and bool(DISCORD_CLIENT_ID and DISCORD_CLIENT_SECRET),
    "steam": AUTH_STEAM_ENABLED and bool(STEAM_API_KEY),
}
ANY_SOCIAL_AUTH_ENABLED = any(SOCIAL_AUTH_ENABLED.values())

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'gdc_storm',
]

if SOCIAL_AUTH_ENABLED["discord"]:
    INSTALLED_APPS.append('allauth.socialaccount.providers.discord')
if SOCIAL_AUTH_ENABLED["steam"]:
    INSTALLED_APPS.append('allauth.socialaccount.providers.steam')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'gdc_storm.rate_limit.RateLimitMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'gdc_kraken.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'gdc_storm' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gdc_storm.context_processors.social_auth_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'gdc_kraken.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('SQLITE_PATH', str(BASE_DIR / 'db.sqlite3')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = os.environ.get("LANGUAGE_CODE", "en-us")

TIME_ZONE = os.environ.get("TIME_ZONE", "Europe/Paris")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = os.environ.get("STATIC_URL", "/static/")
# Ne pas remettre gdc_storm/static ici : AppDirectoriesFinder le trouve déjà
# via l'app installée (sinon doublons collectstatic).
STATICFILES_DIRS = []
STATIC_ROOT = Path(os.environ.get("STATIC_ROOT", BASE_DIR / "staticfiles"))


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

SITE_ID = int(_env("SITE_ID", "1"))
SITE_DOMAIN = (_env("SITE_DOMAIN") or "").strip() or (
    ALLOWED_HOSTS[0] if ALLOWED_HOSTS else "localhost"
)
SITE_NAME = (_env("SITE_NAME") or "GDC Storm").strip()

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_ADAPTER = 'gdc_storm.adapters.AccountAdapter'
SOCIALACCOUNT_ADAPTER = 'gdc_storm.adapters.SocialAccountAdapter'
ACCOUNT_LOGIN_METHODS = {'username'}
ACCOUNT_SIGNUP_FIELDS = ['username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'
if USE_X_FORWARDED_PROTO:
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"
SOCIALACCOUNT_EMAIL_REQUIRED = False
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = False
ACCOUNT_LOGOUT_ON_GET = False

SOCIALACCOUNT_PROVIDERS = {}
if SOCIAL_AUTH_ENABLED["discord"]:
    SOCIALACCOUNT_PROVIDERS["discord"] = {
        "APPS": [
            {
                "client_id": DISCORD_CLIENT_ID,
                "secret": DISCORD_CLIENT_SECRET,
                "key": "",
            },
        ],
        "SCOPE": ["identify", "email"],
    }
if SOCIAL_AUTH_ENABLED["steam"]:
    SOCIALACCOUNT_PROVIDERS["steam"] = {
        "APPS": [
            {
                "client_id": STEAM_API_KEY,
                "secret": STEAM_API_KEY,
                "key": "",
            },
        ],
    }

# Chemins personnalisés pour les fichiers missions et images de mission
MISSIONS_STORAGE_PATH = os.environ.get('MISSIONS_STORAGE_PATH', 'missions')
MISSIONS_IMAGES_STORAGE_PATH = os.environ.get(
    'MISSIONS_IMAGES_STORAGE_PATH',
    (Path('missions') / 'images').as_posix(),
)
MISSIONS_MARKERS_STORAGE_PATH = os.environ.get(
    'MISSIONS_MARKERS_STORAGE_PATH',
    (Path('missions') / 'markers').as_posix(),
)

# Chemin personnalisé pour le stockage des missions (env prioritaire, sinon config.json)
MISSIONS_PBO_STORAGE_PATH = str(Path(_env(
    "MISSIONS_PBO_STORAGE_PATH",
    str(BASE_DIR / "missions_pbo"),
)))

# Fonds de carte OCAP2 (catalogue online + packs locaux)
OCAP_WORLDS_URL = _env('OCAP_WORLDS_URL', 'https://maps.ocap2.com/worlds.json')
OCAP_ARCHIVES_LIST_URL = _env('OCAP_ARCHIVES_LIST_URL', 'https://archives.ocap2.com/list')
# Hotlink navigateur (CDN officiel OCAP2).
OCAP_TILES_BASE_URL = _env('OCAP_TILES_BASE_URL', 'https://maps.ocap2.com')
# Miroir dédié (conteneur ocap-maps-cdn, éventuellement autre serveur).
OCAP_MAPS_CDN_URL = _env('OCAP_MAPS_CDN_URL', '').rstrip('/')
OCAP_MAPS_CDN_SECRET = _env('OCAP_MAPS_CDN_SECRET', '')
_OCAP_MAPS_DEFAULT = (
    '/data/ocap_maps'
    if PLATFORM in ('DOCKER', 'PROD')
    else str(BASE_DIR / 'ocap_maps')
)
OCAP_MAPS_STORAGE_PATH = str(Path(_env('OCAP_MAPS_STORAGE_PATH', _OCAP_MAPS_DEFAULT)))

# Fichiers médias (missions, loadScreen)
_MEDIA_ROOT_DEFAULT = (
    '/data/persist/missions'
    if PLATFORM in ('DOCKER', 'PROD')
    else str(BASE_DIR / 'missions')
)
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', _MEDIA_ROOT_DEFAULT))
MEDIA_URL = os.environ.get('MEDIA_URL', '/media/')

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
        'OPTIONS': {
            'location': str(MEDIA_ROOT),
            'base_url': MEDIA_URL,
        },
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}
# Servir /media/ via Django (nécessaire en Docker sans nginx). Désactiver en PROD si reverse-proxy.
if "SERVE_MEDIA" in os.environ or "SERVE_MEDIA" in config_data:
    SERVE_MEDIA = _env_bool("SERVE_MEDIA")
else:
    SERVE_MEDIA = PLATFORM == "DOCKER" or DEBUG

# For legacy cleaning purposes / gros formulaires
DATA_UPLOAD_MAX_NUMBER_FIELDS = int(os.environ.get("DATA_UPLOAD_MAX_NUMBER_FIELDS", "100000"))
# Limite mémoire avant spill disque pour les uploads (PBO volumineux)
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get("FILE_UPLOAD_MAX_MEMORY_SIZE", str(10 * 1024 * 1024)))
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get("DATA_UPLOAD_MAX_MEMORY_SIZE", str(10 * 1024 * 1024)))
