services:
  web:
    build: .
    ports:
      - "${HOST_PORT:-6130}:8000"
    env_file: .env
    environment:
      SQLITE_PATH: /data/persist/db.sqlite3
      MEDIA_ROOT: /data/persist/missions
    volumes:
      - app_data:/data/persist
      - ${MISSIONS_PBO_HOST_PATH}:/data/missions_pbo
    restart: unless-stopped

volumes:
  app_data:
