# Generated by Django 5.2.16 on 2026-07-19 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdc_storm', '0004_mission_pbo_missing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['mission', 'start_time'], name='gs_mission_start_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['map', 'start_time'], name='gs_map_start_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['start_time'], name='gs_start_time_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['map', 'name'], name='mission_map_name_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['map'], name='mission_map_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['pbo_missing'], name='mission_pbo_missing_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['name'], name='player_name_idx'),
        ),
    ]
