# Generated by Django 5.2.16 on 2026-07-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdc_storm', '0006_audit_constraints_and_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, unique=True, verbose_name='Nom du rôle (brut)')),
                ('category', models.CharField(max_length=100, verbose_name='Catégorie de rôle')),
            ],
            options={
                'verbose_name': 'Catégorie de rôle',
                'verbose_name_plural': 'Catégories de rôles',
                'ordering': ['category', 'role_name'],
            },
        ),
    ]
