# Generated by Django 5.2.16 on 2026-07-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdc_storm', '0008_backfill_rolecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesessionplayer',
            name='role',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
