# Generated by Django 5.2.16 on 2026-07-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdc_storm', '0009_gamesessionplayer_role_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='markers_file',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Chemin fichier marqueurs (JSON)'),
        ),
    ]
